uploads = []
generated = []

[[outputs]]
id = "OdZRlVFxGlSyfeoqea6pb"
uri = "file://the-living-wild-project.tar.gz"
type = "unspecified"
title = "The Living Wild - Project Backup"

[[outputs]]
id = "SvFONRcQBivLdtgn_YmV5"
uri = "file://the-living-wild-project.zip"
type = "unspecified"
title = "The Living Wild - Complete Project Backup (.zip)"

[[outputs]]
id = "Gw0aOnyCWFQBc5qVGDTT0"
uri = "file://report/The-Living-Wild-Usage-Report.md"
type = "text"
title = "The Living Wild - Complete Usage & Analytics Report (Updated)"

[[outputs]]
id = "vkiQb6vsMHCYksqjQVT0n"
uri = "file://report/The-Living-Wild-Usage-Report.pdf"
type = "pdf"
title = "The Living Wild - Usage & Analytics Report (PDF)"
